# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b7c5a032ddf7b0403c6131a7bfb9d1a16361681f5a86737f6501fbdb43f3db00f016e56acb118aa94451ebd3bdd40f581a74d85b8971b94aa87467eac402932

test:
  secret_key_base: 19c13ba03ace6b173f987dafe8d6f968518023be4402c3cfbbf40011733e2fbf9109cf9e611e021bcd6393a4073a1cdf234b5bf850f01dba762067e91696e7d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
